apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    name: appInmueble
    type: netapiInmueble
spec:
  containers:
  - name: app-api
    image: jnino2707/prueba:v1.0
    ports:
      - containerPort: 5000
    env:
      - name: ConnectionStrings__SQLServerConnection
        value: Data Source=mssql-service; Initial Catalog=DBPRUEBA; User Id=sa;password=Aqui la contraseña;Trust Server Certificate=true
